### ISSUE TITLE
Adxl345 wiring

### ISSUE THREAD

**Issue by Freddyb888** [bigtreetech/Manta-M4P#6]
How do I wire a adxl345 on the Manta-M4P with cb1?

**Comment by Aizel330** [comment]
Hi dear, I managed to wired and use an adxl345 using the spi port on the m4p, I'll attach some images, hopefully they are clear enough
![pinout adxl345](https://user-images.githubusercontent.com/117609111/200205827-da401c3c-2052-4e48-b4e6-549d6826a5cb.jpg)
![download](https://user-images.githubusercontent.com/117609111/200205861-704cf92d-d9e8-4840-a2ea-4905fea08178.jpeg)

then basically it's just matter of connecting these pins together and add this to your printer.cfg

[adxl345]
cs_pin: PD9
spi_bus: spi1
axes_map: y,x,z

the axes_map need to be modified depending on the orientation of your particular adxl345 so some testing may be needed to correct the orientation and make sure that the compensation is on the right axes. if anyone needs more infos I'll be more than happy to help.

**Comment by Freddyb888** [comment]
Thanks, but is not possible to connect to the 40 gpio pins that are present on the btt manta m4p with cb1? Thanks again

**Comment by Aizel330** [comment]
https://github.com/bigtreetech/CB1/issues/14#issuecomment-1264667543 I think that could help you with that, hopefully.

**Comment by Freddyb888** [comment]
Thanks a lot. I think it will work.

**Comment by Aizel330** [comment]
no problem, enjoy!

**Comment by ox006** [comment]
how can i connect mpu6050 with M8p/cb1
